services:
  web:
    image: ghcr.io/kanbn/kan:latest
    container_name: ${CONTAINER_NAME:-kan-web}
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-4000}:3000"
    networks:
      - kan-network
      - dokploy-network
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:4000
      - BETTER_AUTH_SECRET=hm8Lwn7PlMm1zn4Xie+nr5c8A/VtNz5qpuQmF+nkwBI=
      - POSTGRES_URL=postgresql://kan:mysupermegasecretpassword@kan-db:5432/kan_db
      - NEXT_PUBLIC_ALLOW_CREDENTIALS=true
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: kan-db
    environment:
      - POSTGRES_DB=kan_db
      - POSTGRES_USER=kan
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - kan_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kan-network

networks:
  kan-network:
  dokploy-network:
    external: true

volumes:
  kan_postgres_data:
